### ISSUE TITLE
使用无效

### ISSUE THREAD

**Issue by liutf** [MadMaxChow/VLOOK#1]
按照教程里做了，但是显示空白，有报错。。请问怎么解决啊？

![image](https://user-images.githubusercontent.com/14069370/44309325-982aee00-a3f7-11e8-993c-ce97e76125a5.png)

![image](https://user-images.githubusercontent.com/14069370/44309330-aed14500-a3f7-11e8-8ef2-deb08dd26d7a.png)

**Comment by MadMaxChow** [comment]
这个报错没关系的，只是webfont加载失败。你试试用项目中带的md文件导出后再试试
