### ISSUE TITLE
MD文件插图支持导出HTML时转为base64存入html文件中

### ISSUE THREAD

**Issue by xiaobailong6** [MadMaxChow/VLOOK#100]

**Comment by MadMaxChow** [comment]
这个需求，对于离线的文档传阅需求，可以用将导出后的HTML和图片直接打包发送。对于在线文档，这样的方式不合适，因为资源都是在线，没有必要进行这样的处理，而且base64后会大大增加文档的容量和流量，影响读者的用户体验
