### ISSUE TITLE
图片缩放以及放大观看

### ISSUE THREAD

**Issue by lipingshan1** [MadMaxChow/VLOOK#105]
对于在`typora`中使用`zoom`缩放后的图片，导出`vlook_hmtl `后,图片操作按钮就乱跑。
![image](https://github.com/MadMaxChow/VLOOK/assets/44493305/babbbae2-0def-4c5f-a218-de443722ddae)
![image](https://github.com/MadMaxChow/VLOOK/assets/44493305/8698021b-3281-4148-83e5-55724e520b24)
图片大小以及放大观看 这是 最基本的需求。

**Comment by MadMaxChow** [comment]
你好，能详细说一下你的 md 文档内容吗？我看看你 zoom 的使用方式

**Comment by lipingshan1** [comment]
您好，过程是这样的：
1. 在 typora中 新的一行，Ctrl + shift + i 引入了图片
2. 然后添加一下题注 '![这是题注](xxxx)'
3. 接着感觉图片太大，就是用typora 的缩放
4. 最后就是这个样子：
   
'<img src="img/00e93901213fb80ee6d4b0260aa4ee25b83894bf.jpeg" alt="美女图片-上题注" title="图片_下题注" style="zoom:50%;" />'

6. 问题。导出vook_html之后，就是我提的issue.
7.  难道设置图片的大小的姿势不对？

**Comment by MadMaxChow** [comment]
谢谢你的反馈。知道原因了，用 zoom 来进行缩放目前已不是 W3C 非标准的方式了，所以也没有对这个做支持。如果你希望对大图做缩小，VLOOK 可以在后面增加一个图片路径的扩展标识来实现，例如可能会像 xxx.png?w=50%，或是 xxx.png?w=300px

**Comment by lipingshan1** [comment]
【xxx.png?w=50%，或是 xxx.png?w=300px 】
试了一下，并没有用。
也许是typora 版本的问题。希望能适配一下。
我当前typora的版本是（1.3.8）：
![image](https://github.com/MadMaxChow/VLOOK/assets/44493305/8bafdb67-1e8e-408c-b047-b9a6f9b7c817)

还有个问题就是，我如果使用\<img src="" />引入图片，如果该图片被其他html标签包裹，其就会被vlook认为是'非插图'，然后
vlook_html 列表中也不显示。这不符合我的本意。
我看了说明文档，使用#logo 或者#icon 等 表示 “非插图”，那么其他没有标识的，不就应该默认是插图，然后在vlook_html图片列表中显示的么？

当然，我还是希望能解决，我最开始提的issue 中的问题。那个操作菜单，都跑的没影了。以及，那个放大按钮，根本就不是放大，也不是显示原图。那它的作用是什么？

**Comment by lipingshan1** [comment]
那期待你的更新。
thinking 这个主题设计的不错。也有一些我个人感觉可以优化的地方：
1.标题字体离散。英语单词离散成字母，不太习惯。我自己本地是给改掉了。
2.封面在typora大纲栏中显示 “一堆 ” 。不知道是不是因为我之前配置标题序号的原因。
总之，感谢你无私地将自己劳动成果，免费分享给需要的人。希望vlook 能够迭代的更加完美。

**Comment by MadMaxChow** [comment]
谢谢你的反馈～近一年没有更新，最近心血来潮更新了一下，还有一个版本也在路上了，预计这个月能再更新版。

1、标题字体因为之前统一设置了字距，对于英文可能是不太友好。对于中文感觉不可以，可以考虑取消。
2、你说的在 Typora 大纲栏显示「一堆」，应该是第一项吧？那个是封面的内容，暂时未找到合适的方式进行缩略简化显示，不影响功能使用。

**Comment by MadMaxChow** [comment]
> 那期待你的更新。 thinking 这个主题设计的不错。也有一些我个人感觉可以优化的地方： 1.标题字体离散。英语单词离散成字母，不太习惯。我自己本地是给改掉了。 2.封面在typora大纲栏中显示 “一堆 ” 。不知道是不是因为我之前配置标题序号的原因。 总之，感谢你无私地将自己劳动成果，免费分享给需要的人。希望vlook 能够迭代的更加完美。

最新的 V17.0 已发布，对于 Typora 的大纲也进行重新调整，建议你去体验一下，应该能满足你

**Comment by lipingshan1** [comment]
刚更新，粗略体验了一下，还不错。
如果不介意的话，使用过程中如果发现新的问题，我也会收集整理，做出反馈。
这个版本，看你列出的更新内容还挺多的。加油👍。

**Comment by MadMaxChow** [comment]
> 对于在`typora`中使用`zoom`缩放后的图片，导出`vlook_hmtl `后,图片操作按钮就乱跑。
> ![image](https://user-images.githubusercontent.com/44493305/238242150-babbbae2-0def-4c5f-a218-de443722ddae.png)
> ![image](https://user-images.githubusercontent.com/44493305/238242489-8698021b-3281-4148-83e5-55724e520b24.png)
> 图片大小以及放大观看 这是 最基本的需求。

目前 VLOOK 20(beta) 已添加了对图片缩放方面的支持，你有兴趣进行试用反馈的话，可以邮件给我体验一下 maxchow#qq.com

**Comment by MadMaxChow** [comment]
目前 VLOOK 20 已发布，已提供更友好的图片缩放排版支持，请前往下载体验，谢谢
