### ISSUE TITLE
typora 使用vlook 的主题会卡死

### ISSUE THREAD

**Issue by lipingshan1** [MadMaxChow/VLOOK#107]
typora 使用vlook 的主题如果打开两到三个md 文档，过一会儿，再打开md文档，就会卡死(不是偶尔，是经常性的)。
而使用github.css 主题就不会。
每一次卡死，只能关掉所有md 文档，或者资源管理器中强制结束任务。
这很致命。
不知道是不是因为使用vlook 主题（vlook thinking）的缘故。

**Comment by MadMaxChow** [comment]
能具体再说一下你使用的操作系统版本、Typora 的版本吗？我看能不能重现

**Comment by lipingshan1** [comment]
win10 的操作系统，typora的版本为 1.3.8.

**Comment by MadMaxChow** [comment]
是所有 md 文档都会卡吗？还是有特定内容的？或是特定大小的？如越过 2w 字？

**Comment by lipingshan1** [comment]
我打开的是两个guide,然后过了一会，再打开一个做笔记的md，就会卡。如果其他人没有反馈，那可能是版本的问题吧。我使用的主题是那个thinking 主题。这个主题还不错。

**Comment by zfm1997** [comment]
确实会出现卡死，在打开一个vlook主题的md后，再打开其他md就会出现

文档字数并不多，以模板文件打开就会这样

**Comment by MadMaxChow** [comment]
@lipingshan1 @zfm1997 二位方便把假死的具体操作过程、表现、影响的范围补充更详细一些吗？我希望找到重现的情况，以便进一步判断原因，谢谢
