### ISSUE TITLE
折叠引用以及彩虹标签失效

### ISSUE THREAD

**Issue by magiceses** [MadMaxChow/VLOOK#109]
折叠引用失效
<img width="307" alt="image" src="https://github.com/MadMaxChow/VLOOK/assets/50326171/3de675c4-bea0-4c53-80e0-b69c23bfcfbb">

彩虹标签失效
<img width="250" alt="image" src="https://github.com/MadMaxChow/VLOOK/assets/50326171/d273b6c0-cb36-4065-99ba-85477025647c">

**Comment by MadMaxChow** [comment]
是不是没有正确安装 VLOOK 插件到 Typora 的导出配置中？
你先按手册检查一下，具体点击[这里](https://madmaxchow.github.io/VLOOK/index.html)

**Comment by magiceses** [comment]
导出后可以了👍，但是使用typora应用Vlook主题包，无法在typora中预览显示，请问这个是typora下的限制吗，不支持这个语法？

**Comment by MadMaxChow** [comment]
很多交互性比较强的特性都得导出为 HTML 才会生效，目前 Typora 未开放相关的机制
