### ISSUE TITLE
单行LaTeX公式实时预览为白色，看不见公式

### ISSUE THREAD

**Issue by jxyz123** [MadMaxChow/VLOOK#112]
Win 11 22H2，VLOOK 17-18，Typora 1.5.5，单行LaTeX公式无法实时预览
![01](https://github.com/MadMaxChow/VLOOK/assets/10681050/7456ac22-196d-4f84-8760-1265c897a06c)

**Comment by MadMaxChow** [comment]
谢谢反馈，这是这个已知的样式问题，主要影响在 Typora 编辑公式时的预览，对阅读和导出HTML影响不大，会在下个版本安排修复

如须紧急使用，可按以下操作：
1. 打开你使用的主题文件，并搜索内容 `#write .code-tooltip` 
2. 然后将其后的 `background: var(--d-f-c)` 替换为 `background: var(--pn-c)`
3. 保存并重新打开 md 文档即可
