### ISSUE TITLE
导出后无法展示

### ISSUE THREAD

**Issue by BensonMax** [MadMaxChow/VLOOK#115]
![image](https://github.com/MadMaxChow/VLOOK/assets/31434954/f1553dc8-ea3d-4ab6-9346-fd680fdf5de3)

导出后md内容无法展示

win11
![image](https://github.com/MadMaxChow/VLOOK/assets/31434954/44284eaa-c3c6-416a-8511-c0b87104661a)

**Comment by MadMaxChow** [comment]
应该是导出前没有正确配置 Typora 的「导出配置」，详细请先参考[这里](https://madmaxchow.github.io/VLOOK/index.html#安装与使用)了解配置安装的方式
