### ISSUE TITLE
表格仍然无法合并单元格是什么原因？

### ISSUE THREAD

**Issue by bcxyf123** [MadMaxChow/VLOOK#116]
模板复制到了typora的主题目录下，typora也更新到了最新版，表格还是无法合并单元格
![image](https://github.com/MadMaxChow/VLOOK/assets/43874559/4c8a68fd-8c85-4509-afc1-84419b05aa60)
![image](https://github.com/MadMaxChow/VLOOK/assets/43874559/5466bce4-c938-4508-895b-61091e7f7255)

**Comment by MadMaxChow** [comment]
导出 HTML 后就可以生效，配置 Typora 的「导出配置」的方式详细见[这里](https://madmaxchow.github.io/VLOOK/index.html#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8)了解配置安装的方式
