### ISSUE TITLE
请问许多特性是否只针对导出为HTML格式生效，而对MD文件不生效？

### ISSUE THREAD

**Issue by BrazilAmando** [MadMaxChow/VLOOK#118]
如刮刮卡、折叠等在typora中均无效，折叠效果导出为html文件后有效，刮刮卡功能导出后也无效。
typora版本： windows 1.7.4版
![image](https://github.com/MadMaxChow/VLOOK/assets/125205627/183f64fc-c79b-4ffa-abf8-29c10c9035bd)

**Comment by MadMaxChow** [comment]
初步判断你应该没有配置好对应的「导出配置」，你详细看看和检查以下链接中的「安装与使用」的说明：

[VLOOK 简介 - 安装与使用](https://madmaxchow.github.io/VLOOK/index.html#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8)
