### ISSUE TITLE
大大，字体在哪鸭？

### ISSUE THREAD

**Issue by oinjser** [MadMaxChow/VLOOK#119]

**Comment by MadMaxChow** [comment]
你具体的诉求是吗？如果你说的是 VLOOK 中的字体主题，是不用下载的，是使用了 webfont，有三个使用方法：
1、导出 HTML 后按键盘[A]，或点击右下角的字体主题按钮进行选择/切换
2、在访问的 HTML 地址后添加 URL Query 参数 `wf` 指定，如：`xxx.html?wf=serif` ，则指定使用 `文艺范` 字体主题
3、如果导出的 HTML 默认指定为非默认字体主题，可通过私人定制主题的方式激活
