### ISSUE TITLE
release下模版文件资源乱码

### ISSUE THREAD

**Issue by lleiwang** [MadMaxChow/VLOOK#120]
`released/released/VLOOK-Document-Template-doc_lib.md`及`released/released/VLOOK-Document-Template.md`
两文件乱码
麻烦及时修复~

如图：
<img width="500" alt="image" src="https://github.com/MadMaxChow/VLOOK/assets/8375948/7ee462a8-4798-42de-b7a1-746b9a3a89c5">

**Comment by MadMaxChow** [comment]
谢谢反馈～
那两个文件是比较简单的示例，更多的示例文档请看 demo 这个目录下的 md 文件～
乱码的已更新到仓库，在后续发布的新版会重新打包
