### ISSUE TITLE
在Typora编辑界面无法显示彩虹文本

### ISSUE THREAD

**Issue by Fred-supre** [MadMaxChow/VLOOK#123]
**Describe the bug**
在Typora编辑界面使用类似这样的语法：**指定的加粗文本内容**~(RoBuAq)~
在编辑器中无法显示彩虹文本，但是导出之后可以正常显示。

Typora内：
<img width="630" alt="image" src="https://github.com/MadMaxChow/VLOOK/assets/57496712/2023ed5a-3cc7-4163-a8ff-6f23abe2198c">

导出后：
<img width="715" alt="image" src="https://github.com/MadMaxChow/VLOOK/assets/57496712/13460dd4-b7ae-4d1b-b383-2b0571e9d855">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser：chrome
 - Typora：1.8.10 (7132)

**Comment by MadMaxChow** [comment]
谢谢反馈。目前的机制是只能在导出后的 HTML 才能生效，在编辑时只能突出格式标记内容
