### ISSUE TITLE
请问有办法能兼容嵌入html吗？

### ISSUE THREAD

**Issue by MathhubDouglas** [MadMaxChow/VLOOK#124]
**Describe the bug**
当嵌入html模块后插件无法加载出来
**To Reproduce**

**Expected behavior**
当嵌入html模块后插件无法加载出来
```
<p>
<div style="width:100%;text-align:center">
	<iframe allowtransparency="yes" frameborder="0" width="300" height="560" src="https://mathhubdouglas.github.io/" />
</div>
</p>
```

经测试应该不是typora的bug，其中github主题导出html可以显示

**Screenshots**
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/a405d959-60ee-4ad9-bd9b-8c62ceb5dd8b)
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/05b469cd-3ce4-4972-9728-c020c4ddf759)
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/f69226f2-da80-440e-8a5a-e69744bb597a)
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/48c3de54-0678-4237-bbd8-bc9fcb467d7c)

**Desktop (please complete the following information):**
win10+chrome+23
**Smartphone (please complete the following information):**

**Additional context**

**Comment by MadMaxChow** [comment]
你的嵌入方式是怎么做的？同时把浏览器控制台的输出也提供出来看看

**Comment by MathhubDouglas** [comment]
> 你的嵌入方式是怎么做的？同时把浏览器控制台的输出也提供出来看看

我是先用gitpage部署了一个网页<https://mathhubdouglas.github.io/>，在md文件中然后用
```html
<p>
<div style="width:100%;text-align:center">
	<iframe allowtransparency="yes" frameborder="0" width="300" height="560" src="https://mathhubdouglas.github.io/" />
</div>
</p>
```

引入网页
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/a0f42691-dde8-4ad1-81c9-24bb31bf3669)

github主题且html导出
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/ecca5b2c-40b8-48b7-b6a3-4bb8a0684273)

vlook
![image](https://github.com/MadMaxChow/VLOOK/assets/132361107/a33e7675-ba1f-4057-a426-e17763355f5f)
