### ISSUE TITLE
vlook Geek主题 大纲的编号和正文的编号不一致

### ISSUE THREAD

**Issue by lightzhoulin** [MadMaxChow/VLOOK#127]
![11111](https://github.com/MadMaxChow/VLOOK/assets/8384492/ff9fd07d-bd12-4e56-90a9-9b8f6cb35b73)

**Comment by lightzhoulin** [comment]
![Uploading 微信图片_20240530114035.png…]()

**Comment by MadMaxChow** [comment]
可以提供一下你的md文件吗？我看能不能重现这个问题

**Comment by lightzhoulin** [comment]
![image](https://github.com/user-attachments/assets/469cf84c-0503-46f9-a883-7e364ecf3f56)

**Comment by lightzhoulin** [comment]
[Mysql学习.md](https://github.com/user-attachments/files/16690066/Mysql.md)

**Comment by lightzhoulin** [comment]
文件提供了

**Comment by lightzhoulin** [comment]
![image](https://github.com/user-attachments/assets/1fe710fa-5608-4a82-9c08-e5edc8573671)

**Comment by lightzhoulin** [comment]
[Test.md](https://github.com/user-attachments/files/16690147/Test.md)

**Comment by MadMaxChow** [comment]
不是主题的问题，是你的 md 文档中标题出现了断层导致的。
如：## 基础命令学习 ，这个是二级，正常其下级应该是三级「###」，但你的查询用户连接数是四级「####」了
你调整一下不要出现断层就会正常～
