### ISSUE TITLE
侧边栏目录没有成功生成，是什么原因导致的？

### ISSUE THREAD

**Issue by woshiamiaojiang** [MadMaxChow/VLOOK#29]
![Snipaste_2019-11-02_11-04-29](https://user-images.githubusercontent.com/12020661/68065201-b52fb080-fd60-11e9-88f7-6627e350b86a.png)
![Snipaste_2019-11-02_11-04-39](https://user-images.githubusercontent.com/12020661/68065203-b95bce00-fd60-11e9-83a4-d938300102f5.png)

**Comment by sdvdxl** [comment]
正文开始前加  [TOC] 试试

**Comment by MadMaxChow** [comment]
你参考demo目录中的模板文件的写法来试试
`3-demo/VLOOK-Template 文档模板.md`

https://github.com/MadMaxChow/VLOOK/blob/master/3-demo/VLOOK-Template%20%E6%96%87%E6%A1%A3%E6%A8%A1%E6%9D%BF.md

**Comment by woshiamiaojiang** [comment]
加了[TOC]成功了，谢谢各位。
