### ISSUE TITLE
使用插件之后，左侧目录栏，不显示

### ISSUE THREAD

**Issue by kooksee** [MadMaxChow/VLOOK#47]
![image](https://user-images.githubusercontent.com/6829652/72199324-719aa680-3475-11ea-83ff-d2fa8943e33e.png)

显示的效果不是很好
不过，markdown的正文效果很好，非常感谢

**Comment by MadMaxChow** [comment]
你用的是 Typora 吧，Typora 的大纲页板和文件页板是不能同时显示的，你切换一下就可以

**Comment by kooksee** [comment]
嗯嗯，好的，多谢。我尝试了一下，还是不行，左侧的颜色，无论切换成文件还是大纲模式，都是白色的，不知道怎么回事

**Comment by MadMaxChow** [comment]
你的系统是不是设置了 Dark Mode，目前 Typora 对 Dark 的支持不是很好，所以没有将针对 Typora 在 Dark Mode 试验性的样式加入到 VLOOK 中，已重新打包了一个更新，你重新下载体验一下吧
