### ISSUE TITLE
请问svg log 文件有工具生成嘛 

### ISSUE THREAD

**Issue by ldflovewr** [MadMaxChow/VLOOK#51]
我只有png的log

**Comment by MadMaxChow** [comment]
请教一下 SVG LOG 文件，和 PNG LOG 文件是什么来的？提供几个样板看看么

**Comment by ldflovewr** [comment]
![log](https://user-images.githubusercontent.com/61726674/76183198-9ce60b80-6202-11ea-8112-4441ac4c76d2.png)
@MadMaxChow 这个是png log

**Comment by MadMaxChow** [comment]
这就是一个普通的PNG文件吧？你说的LOG是什么意思？

**Comment by ldflovewr** [comment]
> 这就是一个普通的PNG文件吧？你说的LOG是什么意思？

就是png log 转  svg log
