### ISSUE TITLE
生成的html文档，MacOS系统无法复制代码

### ISSUE THREAD

**Issue by wangvic21** [MadMaxChow/VLOOK#54]
选择复制代码，MacOS复制代码块内容提示失败。
若` var text = document.createElement('input');`，则支持复制为单行。

**Comment by MadMaxChow** [comment]
> 选择复制代码，MacOS复制代码块内容提示失败。
> 
> 若` var text = document.createElement('input');`，则支持复制为单行。

说的是代码块的复制吗？你的浏览器是那个？什么版本？
另，同时方便把你的文件发给我吗？maxchow@qq.com

**Comment by wangvic21** [comment]
您好：

是的，复制代码块。

版本： MacOS：10.15.4 (19E287)
	Safari：版本13.1 (15609.1.20.111.8)

附件是源文档和生成的html。比较奇怪的是为什么参考文献会显示在网页最上方。多语言系统不是应该解析出系统语言，然后显示出一种么？

复制提示：

**Comment by MadMaxChow** [comment]
能重现你说的问题了，谢谢反馈，建议你先用 chrome / firefox 进行访问，这两个浏览器都不存在这个问题。
