### ISSUE TITLE
目前左侧侧边栏，会随着滚动条拖拉隐藏和消失，如何设置左侧目录一直保持不消失，一直存在

### ISSUE THREAD

**Issue by easytrack-docker** [MadMaxChow/VLOOK#56]
目前左侧侧边栏，会随着滚动条拖拉隐藏和小时，如何设置左侧目录一直保持不消失，一直存在
![image](https://user-images.githubusercontent.com/30903393/83992090-a148ce80-a981-11ea-8fa3-b1ce640a6618.png)
![image](https://user-images.githubusercontent.com/30903393/83992120-bf163380-a981-11ea-9034-b4042b6daa25.png)

**Comment by MadMaxChow** [comment]
滚动到第1章之后，就会自动固定在左边，除非你手动关了，回到封面就会自动重新隐藏的

**Comment by eunrui** [comment]
如何设置保持不动呢 不想动诶

**Comment by MadMaxChow** [comment]
目前的设计暂时是这样，为了能更好地展示封面的内容和信息，在封面时会自动收起，滚动到第1章正文后会自动打开，也可点击按钮或按O键打开或关闭。
你希望保持自动一直显示的具体原因是什么呢？

**Comment by eunrui** [comment]
> 目前的设计暂时是这样，为了能更好地展示封面的内容和信息，在封面时会自动收起，滚动到第1章正文后会自动打开，也可点击按钮或按O键打开或关闭。
> 你希望保持自动一直显示的具体原因是什么呢？

首先呀我是做个文档嘛，封面其实可有可无，这个自动打开要在第一章节的标题过去两行才会出来，个人体验很难受一个东西弹来弹去的，我只是讲一下我的产品体验，您不要生气，东西很棒的，功能也很全呀，只不过没法自定义一下功能的选择，就是希望简单点，还有light和dark的mode切换，很不希望他自动切换，看了下js试了下也不知道怎么可以默认到light不根据浏览器来自动适配，还有结束语哪里，粘贴复制template都不行，只有自己手输入六级标题才能被识别。em，或许有什么设定方式是我不知道的吗，文档里貌似没有看到诶。麻烦您了呀，如果有解决方式的话，谢谢！~

**Comment by MadMaxChow** [comment]
你说的部分需求，目前就已经有对应的解决办法，具体加入 VLOOK 的群沟通吧～QQ 群：805502564
