### ISSUE TITLE
封面页标题问题

### ISSUE THREAD

**Issue by QiangZiBro** [MadMaxChow/VLOOK#57]
您好，感谢开源！我尝试了下目前最新版本，感觉封面页标题比以前低了，标题几乎在页面一半的地方，导致封面页主要内容聚集在页面下半部分，导出的pdf美观度不是很高。不知作者怎么看呢？

**Comment by MadMaxChow** [comment]
你是使用哪个主题？因为不同主题的设置不同的，同时你也可以根据自己实际情况进行一些自定义修改。具体就是修改主题的CSS文件
