### ISSUE TITLE
植入后浏览器出现错误提示

### ISSUE THREAD

**Issue by WangJiyuanYo** [MadMaxChow/VLOOK#58]
植入插件后，浏览器打开报错。。不知道该怎么解决。。
![image-20200805100934372](https://user-images.githubusercontent.com/22519258/89364638-7a024980-d705-11ea-88fe-ac3a64942444.png)

**Comment by MadMaxChow** [comment]
> 植入插件后，浏览器打开报错。。不知道该怎么解决。。
> ![image-20200805100934372](https://user-images.githubusercontent.com/22519258/89364638-7a024980-d705-11ea-88fe-ac3a64942444.png)

图片显示不出来，方便的话发我邮箱 maxchow#qq.com，或是入Q群反馈一下：805502564

**Comment by MadMaxChow** [comment]
以上提示是说缺少封面、文档目录、封底，这是因为你没有按 VLOOK 插件的标准模板来编写 MD 文档。
你可以项目中的文档模板为基础进行 MD 文档的编写。
文档模板位于：`released\文档模板-Template.md`
