### ISSUE TITLE
希望增加窄屏模式，提升阅读体验

### ISSUE THREAD

**Issue by iblueer** [MadMaxChow/VLOOK#59]
每一行的文字过长会导致阅读时容易串行，产生视觉疲劳，希望可以增加窄屏模式。

**Comment by MadMaxChow** [comment]
非常感谢你的建议，这个特性也有考虑过，但没有平衡好具体的方案，临时来说你可以开启浏览器自适应布局（手机、平板模式），目前 VLOOK 也是支持移动端显示的。

另外，你能否提供一些更具体的建议，希望是做成什么样的窄屏模式？

**Comment by iblueer** [comment]
我想的效果大题是这样的：正文container，width=40%，margin-left和margin-right都auto。
具体的您可以看一下notion家做的窄屏模式和宽屏模式。
如果您不用notion，也可参考一下微信公众号文章在PC端打开的样式。

**Comment by MadMaxChow** [comment]
大概明白你的意思了，这个后续会进行适当优化调整，谢谢反馈～比心
