### ISSUE TITLE
表格合并和标签未生效

### ISSUE THREAD

**Issue by lovelifestar** [MadMaxChow/VLOOK#60]
typora版本：mac 0.9.9.32.1 (4191)
vlook版本：9.19
https://tva1.sinaimg.cn/large/007S8ZIlly1gi2wv4hc93j31ny0e4jvg.jpg
https://tva1.sinaimg.cn/large/007S8ZIlly1gi2wvjpprhj31340bedjg.jpg
https://tva1.sinaimg.cn/large/007S8ZIlly1gi2wvovl2aj30pu0lyq5v.jpg

**Comment by MadMaxChow** [comment]
在 Typora 编辑状态是不能生效的，需要导出为 HTML 后，植入 VLOOK 插件就可以
