### ISSUE TITLE
vlook插件检测不到封底情况

### ISSUE THREAD

**Issue by wuli-taotao-zhen** [MadMaxChow/VLOOK#62]
The VLOOK plugin cannot be activated for the following reasons:
Missing "Back cover"content that meets VLOOK specifications
Suggestion Reference document template:
released/VLOOK-Document-Template.md	

由于以下原因，无法激活VLOOK插件：
缺少符合VLOOK规范的“封底”内容
建议参考文件模板：
发布/VLOOK文档-模板.md

在typora中显示
![image](https://user-images.githubusercontent.com/34727286/93416096-a51cb300-f8d7-11ea-9636-f0a851fb4857.png)

HTML文件显示
![image](https://user-images.githubusercontent.com/34727286/93416147-c2518180-f8d7-11ea-9af0-6bd2dcf227f5.png)

错误显示
![image](https://user-images.githubusercontent.com/34727286/93416197-da290580-f8d7-11ea-87ad-ccc22020ec92.png)

**Comment by wuli-taotao-zhen** [comment]
在文档最前，添加了vlook要求的封面和toc，在文档的最后按照vlook要求添加了封底。但是导出为html文件之后vlook检测不到封底并报错，但是在Chrome浏览器打开导出的html文件在页面的最后可以看到封底的存在。

**Comment by wuli-taotao-zhen** [comment]
typora版本：0.9.96
vlook版本：9.23

**Comment by wuli-taotao-zhen** [comment]
使用上面同版本的导出模版文件添加vlook插件
chrome显示情况
![image](https://user-images.githubusercontent.com/34727286/93417368-8b309f80-f8da-11ea-9e6b-5fa4b6fd176c.png)

**Comment by wuli-taotao-zhen** [comment]
文档行数 1w3行，检测不到封底和行数过多有关系吗？

**Comment by wuli-taotao-zhen** [comment]
控制台输出
![image](https://user-images.githubusercontent.com/34727286/93418125-3ee65f00-f8dc-11ea-8d32-a595a592e65b.png)

**Comment by wuli-taotao-zhen** [comment]
模版文件导出的html文件控制台输出
![image](https://user-images.githubusercontent.com/34727286/93418221-76eda200-f8dc-11ea-8921-36460d2aa787.png)

**Comment by wuli-taotao-zhen** [comment]
谢谢作者，插件很强大！问题解决了，使用作者提供的模版将内容替换之后可以显示侧边栏了。

**Comment by eunrui** [comment]
替换模板也不显示诶 还有其他解决方案吗 怎么都检测不到封底

**Comment by eunrui** [comment]
> 替换模板也不显示诶 还有其他解决方案吗 怎么都检测不到封底

直接输入###### xxx文字 直接保存解决了... 无语
