### ISSUE TITLE
能不能修改下不同标题级别的UI

### ISSUE THREAD

**Issue by w454196785** [MadMaxChow/VLOOK#63]
现在1到4级标题的样式都是一样的,写完文档后不容易区分章节,层次感不太好
![image](https://user-images.githubusercontent.com/31468811/97138864-1b90b880-1794-11eb-98da-63ab11e287f9.png)

建议把2级3级和4级标题格式修改下.
我本地修改了一下,感觉层次清晰了一些,但是不太好看
![image](https://user-images.githubusercontent.com/31468811/97138935-4ed34780-1794-11eb-9e54-bcdd3312d730.png)

**Comment by MadMaxChow** [comment]
目前1－4级的标题样式是有区别的，字号不同，前面的章节号级数也不同。这样的区分已足够明显了吧
