### ISSUE TITLE
为什么导入typora后都是黑色主题呀

### ISSUE THREAD

**Issue by Achuan-2** [MadMaxChow/VLOOK#64]

**Comment by MadMaxChow** [comment]
你的系统配置的主题是不是 Dark？VLOOK 的主题都支持自适应的，方便的话上个图或描述具体一点，或是在 VLOOK 的 QQ 群沟通反馈：805502564

**Comment by Achuan-2** [comment]
是的，确实把系统主题改为浅色就好了，抱歉打扰了
