### ISSUE TITLE
为什么我用demo下的“VLOOK 快速参考手册”文件导出HTML在浏览器上打开没有右侧的导航栏呢

### ISSUE THREAD

**Issue by caoyingde** [MadMaxChow/VLOOK#65]
为什么我用demo下的“VLOOK 快速参考手册”文件导出HTML在浏览器上打开没有右侧的导航栏呢

![image](https://user-images.githubusercontent.com/10750404/99037008-c7703b80-25bd-11eb-9276-ad6e8e4e6911.png)

**Comment by MadMaxChow** [comment]
因为网络原因我看不到图，一般看不到导航栏，原因是没有激活VLOOK，没有激活VLOOK，一般原因是 MD 文档不符合模板规范，没有按规范添加封面、封底，或是没有添加 `[TOC]` 标记。
具体你以 released 目录下的 vlook-template.md 文件为参考来改写吧～
谢谢支持！
