### ISSUE TITLE
mermaid 流程图显示的文字不完整

### ISSUE THREAD

**Issue by yreme** [MadMaxChow/VLOOK#66]
在typora的vlook  主题下,mermaid主题都不能正常显示完整的文字.

例如geek
![vlookimage](https://user-images.githubusercontent.com/6118517/102160825-22e56000-3ec1-11eb-898d-532616f86abe.jpg)

正常的github主题效果
![github-result](https://user-images.githubusercontent.com/6118517/102160927-59bb7600-3ec1-11eb-9924-80f9328950ce.jpg)

这是我所用的流程图源码
```mermaid
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

附件是 github的theme 文件
[github-themes.zip](https://github.com/MadMaxChow/VLOOK/files/5692937/github-themes.zip)

**Comment by yreme** [comment]
mermaid 流程图复现的调用代码
![flow-code](https://user-images.githubusercontent.com/6118517/102161347-23cac180-3ec2-11eb-80e8-6bd46a0400ca.jpg)

**Comment by MadMaxChow** [comment]
因为网络问题我暂时看不到图片。
你的电脑是 Windows 吗？是不是开高分辨率 （High DPI）？如果是话这是 Mermaid 的 BUG。目前 VLOOK 是有针对这个情况做非官方的修正的。

**Comment by yreme** [comment]
系统是mac , 显示屏幕为  (2880 × 1800) .

我使用typora的github 主题,可以正常显示 Mermaid,其他主题也可以正常显示 . 

只有vlook主题会掉链子.

**Comment by MadMaxChow** [comment]
是否方便加入 VLOOK 的 Q 群沟通一下？805502564

**Comment by yreme** [comment]
感谢,已经申请加群
