### ISSUE TITLE
导出PDF特效丢失比较多

### ISSUE THREAD

**Issue by liuxfn** [MadMaxChow/VLOOK#68]
html输出确实非常炫，但是导出PDF的特性丢失得比较多，比如表格合并就没了，有无可能实现一下！

**Comment by MadMaxChow** [comment]
如果你要使用 PDF，建议你导出 HTML 后，用浏览器打开，然后用浏览器的导出/打印成 PDF，这样就能保留绝大部分的特性。

**Comment by crazyStar00** [comment]
> 如果你要建议你导出 HTML，然后用浏览器打开，然后浏览器的导出/打印成 PDF，这样的话就可以使用 PDF 了。

但这样导出的pdf没有了书签目录，可以解决吗？
