### ISSUE TITLE
页内跳转不支持锚点方式

### ISSUE THREAD

**Issue by douhapy** [MadMaxChow/VLOOK#69]
9.23版本，页内跳转不支持锚点方式（typora是支持的）

如定义一个锚点，<span id="jump">Hello World</span>
使用markdown的语法:[XXXX](#jump)

转换成html，用了该版本的插件，提示无效页内跳转。

这个能否改进下？

**Comment by MadMaxChow** [comment]
目前已发布了最新的 10.0 版本再试试，应该是已解决这类问题了
