### ISSUE TITLE
应用主题后左侧菜单栏图标无法显示

### ISSUE THREAD

**Issue by TakiGuan** [MadMaxChow/VLOOK#70]
已经安装字体

![image.png](https://i.loli.net/2021/02/23/bxu4I1syrV9MUeg.png)

**Comment by MadMaxChow** [comment]
Typora 显示大纲的话，是通过菜单「显示 - 大纲」来打开

**Comment by TakiGuan** [comment]
这是`File Tree View`，并非大纲视图，是否是因为`Tree View`中用了特殊的字体显示图表，如果系统没有安装该字体，无法正常显示？

**Comment by MadMaxChow** [comment]
初步判断应该是跟 Typora 的样式有冲突，正在跟 Typora 沟通，会尽快发布更新，非常你的反馈

**Comment by MadMaxChow** [comment]
> 这是`File Tree View`，并非大纲视图，是否是因为`Tree View`中用了特殊的字体显示图标，如果系统没有安装该字体，无法正常显示？

已确定原因了，你将主题 CSS 中的这行删除就可以：
`@import url("https://cdn.bootcss.com/font-awesome/5.11.2/css/all.min.css");`

或是改为：
`@include-when-export url("https://cdn.bootcss.com/font-awesome/5.11.2/css/all.min.css");`

近期会发个小修复的版本，谢谢反馈
