### ISSUE TITLE
如果针对 docsify 进行适配,一定是绝配!

### ISSUE THREAD

**Issue by Jonnyan404** [MadMaxChow/VLOOK#71]
官网: <https://docsify.js.org/#/?id=docsify>

这个可以在运行时解析md文件,也就是我们只管写md,网页就会自动呈现效果了.
不用像这些编辑器那么麻烦,还要再次导出,尤其是更新内容的时候!

**Comment by Mantyke** [comment]
同意，如果能适配会是非常适合docsify的增强
