### ISSUE TITLE
表格单元格合并还是无法完成啊？求修复bug

### ISSUE THREAD

**Issue by AweiLoveAndroid** [MadMaxChow/VLOOK#74]
我按文档说明做了两次不同操作，但是在Markdown文件预览里面，都没有达到合并表格效果（导出HTML却可以了，为啥）：

> 操作1：

```
| 标题1   | 标题2    | 标题3    | 标题4    |
| ---- | ---- | ---- | ---- |
|1|1|1|1|
|000|000|000|这个待合并的单元格B==|
|这个待合并的单元格A:|000|000|000|
|1|1|1|1|
|1|1|1|1|
|1|1|1|1|
```

> 输出结果：

![捕获1](https://user-images.githubusercontent.com/27602662/120618051-43b06a80-c48d-11eb-8524-2f0461d0f538.PNG)

> 操作2：

```
| 标题1   | 标题2    | 标题3    | 标题4    |
| ---- | ---- | ---- | ---- |
|1|1|1|1|
|:|000|:|000|
|:|000|:|000|
|1|==|1|<<|
|1|==|1|<<|
|1|1|1|1|
```

》 结果：

![捕获2](https://user-images.githubusercontent.com/27602662/120618190-6b073780-c48d-11eb-8bb3-7388fae62708.PNG)

**Comment by MadMaxChow** [comment]
单元格合并这个特性，目前是必须导出HTML才能生效的。现在TYPOA已经支持导出配置，可以一键导出HTML并应用插件的了，也不会太麻烦，谢谢你的支持！
