### ISSUE TITLE
《快速参考手册》的一个文字错误纠正

### ISSUE THREAD

**Issue by Hoha2333** [MadMaxChow/VLOOK#75]
’‘’
你知道吗？

你正在浏览_**在**_这个 VLOOK™ 快速参考手册，就是由 Typora 编辑并应用 VLOOK™ 插件生成的！AMAZING!!！
‘’‘
**加粗的这个地方，可以把“在”改成“的”，这样比较好。**

**Comment by MadMaxChow** [comment]
为你点赞，看得这么细致！马上更正～
