### ISSUE TITLE
导出后打开没有样式。

### ISSUE THREAD

**Issue by cherryamme** [MadMaxChow/VLOOK#76]
按照文档操作导出demo文件时，edge中打开html没有样式
![image](https://user-images.githubusercontent.com/32868296/125574254-480c5191-3a0d-431a-ba01-dbdd8a6dad37.png)
控制台报错如下：
![image](https://user-images.githubusercontent.com/32868296/125574312-82b073fe-fd98-4f0d-90d3-3b5c6e53ba21.png)

body也设置了：
![image](https://user-images.githubusercontent.com/32868296/125574381-27967358-49dd-44da-a06f-e9e17281d59b.png)

**Comment by MadMaxChow** [comment]
初步判断应该是你创建导出配置时，选用的模板不正确。建议重建一下试试，注意选择「HTML」为模板进行创建，而不是「HTML (Without Styles)」
