### ISSUE TITLE
URL 中同时使用 cs 和 ws=none 会导致只出现封面，无法滚动

### ISSUE THREAD

**Issue by FrankSFLYS** [MadMaxChow/VLOOK#77]
在生成的 html 中使用 URL 参数，指定 `cs=任意` 和 `ws=none`，会导致载入错误，只显示一个封面，无法向下滚动。使用导航按钮定位之后才会恢复正常。
使用示例：`file:///F:/Weixin/x.html?cs=dark&ws=none`

**Comment by MadMaxChow** [comment]
你用的是 V10.7.1 吧？目前在开发中的最新版本已修正这个问题了，已计划在近期发布了

**Comment by MadMaxChow** [comment]
最近发布的 V11.0 已修复以上问题
