### ISSUE TITLE
【feature request】图注/标题放在图的下方

### ISSUE THREAD

**Issue by retsyo** [MadMaxChow/VLOOK#82]
我习惯了，表的标题（带编号的）放在表上方，图的标题（带编号的）放在图下方

typora/vlook咋弄呢？

**Comment by MadMaxChow** [comment]
目前是支持双题注（即上、下题注），下题注的语法在参考指南中有：
![上题注]"下题注"

但对于上题注为空的情况，目前会根据表格内容自动生成，你的这种用法启发了我，对于有下题注的，可以调整为不自动生成。下个版本中就可以提供这个特性～

**Comment by MadMaxChow** [comment]
不好意思，我之前对你的说法理解有偏差。表格、图片的自动编号都是在上方，因为这样更统一，也更利于长图时能直接看到题注。如果你希望在下方显示图的说明，可以参考我上方面的下题注。但编号目前暂时还是只能统一在上方
