### ISSUE TITLE
【feature request】支持注释

### ISSUE THREAD

**Issue by retsyo** [MadMaxChow/VLOOK#83]
# 1. 长话短说
Typora里面的注释，vlook能否别渲染到输出的html中

# 2. 太长费脑
## 2.1 目的
一节文字，有很多段，里面有标题、子标题、多行代码块、文字、图……。某些原因（比如，暂时没写完、针对不同人分发内容），打算把这一节给注释掉
- 最起码，标题、子标题、图等等，不要再显示成对应样式，也别参与编号了
- 之后还能很方便地换回标题、子标题、多行代码块、文字、图……
- 如果能折叠显示，就好了

## 2.2 现状
这部分的主要实现，应该是Typora
我试过
- `<pre>...</pre>`、`<!--   -->`，完全不认
- 三个"`"的多行代码
```
_```  
我不知咋写出三个"`"，所以这里前面加了`_`
这是很多内容的一小节
_```
```
但是Typora在处理嵌套的多行代码时，并不好，所以并没有理解按我的意图，把这长长一节全作为代码，还是遗留了一些代码、图
我也查看了Typora的issue，并没有官方认可的注释的方式

## 2.3 所以这个和vlook啥关系呢？
当然有关系了，vlook得认可某种方式是注释，才可能不在html中输出

**Comment by MadMaxChow** [comment]
Typora 带注释时输出的 HTML 也是没有被排除的，只是没有内容显示，有些样式（如Github）看不明显而已。
对于你说的这种，简单的做法建议是直接先放在别的MD文件中，或在标题中标记清晰属于未完成的内容就可以。
如果你想折叠起来也可以，目前 VLOOK 的引用是支持指定内容进行折叠的，详见参考[这里](https://madmaxchow.github.io/VLOOK/guide.html#%E6%8A%98%E5%8F%A0%E5%90%A7%E5%BC%95%E7%94%A8)
