### ISSUE TITLE
自动题注选项卡 [feature request]

### ISSUE THREAD

**Issue by a224515a** [MadMaxChow/VLOOK#84]
自动题注是非常方便的功能
但有时确实是不需要添加题注 (有时略显杂乱)
能否安排一个选项卡
让用户按需决定是否打开自动题注
选项卡或许可依照图片、表格、代码块等类别各自提供开关

感谢您在此项目付出的精力

**Comment by MadMaxChow** [comment]
可以考虑后面添加对应的启动参数（在文档的 YAML 中添加，参考[这里](https://madmaxchow.github.io/VLOOK/guide.html#%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0)）

具体可能会考虑提供几种选项：
- 全部不启用
- 指定启用针对 1 个或多个类型不启用（如：插图、表格、代码块、多媒体等）

你看这是不是你希望的？

**Comment by a224515a** [comment]
Yes, that is exactly what I need
Thank you
