### ISSUE TITLE
[feature request]支持pandoc导出

### ISSUE THREAD

**Issue by viperasi** [MadMaxChow/VLOOK#88]
使用vlook写文档很赞，也很炫，只是在发布到gitlab的pages时，需要先导出成html才能发布，所以尝试使用pandoc进行导出，页面效果完全不一样，希望能支持pandoc导出，这样就可以在提交内容时通过gitlab-ci自动导出html到public下。

**Comment by MadMaxChow** [comment]
VLOOK 目前的特性需要基于 Typora 导出，基于 pandoc 导出 HTML，这个我可研究一下，你有没有可以供我参考或敲门的资料可以分享？
