### ISSUE TITLE
表格相关的特性无法生效是什么原因？

### ISSUE THREAD

**Issue by allceo** [MadMaxChow/VLOOK#90]
表格相关的特性无法生效是什么原因？
![image](https://user-images.githubusercontent.com/1932516/147544996-fd2273f2-e9d6-4a94-bb25-cced55bd1c4b.png)
![image](https://user-images.githubusercontent.com/1932516/147545028-f6c86dee-0722-44a1-b997-6b2e85583897.png)

**Comment by MadMaxChow** [comment]
配置好 VLOOK 的导出选项后，然后导出 HTML 后就可以生效
[点这里了解一下](https://madmaxchow.github.io/VLOOK/index.html#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8)

**Comment by MadMaxChow** [comment]
配置好 VLOOK 的导出选项后，然后导出 HTML 后就可以生效
[点这里了解一下](https://madmaxchow.github.io/VLOOK/index.html#%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8)

**Comment by allceo** [comment]
无法直接预览吗？只能导出的效果是吧？

**Comment by MadMaxChow** [comment]
> 无法直接预览吗？只能导出的效果是吧？

是的，因为标准的 Mardown 是不支持单元格合并的，所以编辑器也不能实时支持，VLOOK 暂时只能通过这种语法扩展和导出 HTML 后再处理生成
