### ISSUE TITLE
一觉醒来主字体变成斜体了

### ISSUE THREAD

**Issue by FrankSFLYS** [MadMaxChow/VLOOK#91]
昨天还是好的，今天打开 Typora，包括主界面和正文字体，都变成斜体了，除了 VlookHope 和默认主题，其他 Vlook 主题都变成斜体了，是不是用的在线字体出问题了？
![image](https://user-images.githubusercontent.com/10843159/147711467-5ec034c7-7b8d-40cf-b5b3-62e147920adb.png)

![image](https://user-images.githubusercontent.com/10843159/147711549-6dff8876-71ad-44f9-adc8-63d48d10233f.png)

**Comment by MadMaxChow** [comment]
Typora 和 VLOOK 的版本分别是？

**Comment by FrankSFLYS** [comment]
> Typora 和 VLOOK 的版本分别是？

Typora 是 `0.11.18`，VLOOK 是 `V13.0 (2021-12-11)`

**Comment by MadMaxChow** [comment]
未能重现你的问题，建议你重新下载 VLOOK，重新安装一次主题试试（须重新启动 Typora）

**Comment by FrankSFLYS** [comment]
很难受，重新安装主题也没用，我另一个电脑就正常。

**Comment by FrankSFLYS** [comment]
VLOOK 换成 `12.0` 以后恢复正常了

**Comment by MadMaxChow** [comment]
你试对V13的任意主题CSS文件做以下两个操作，看会不会变好：
1、搜索内容「.md-comment」，可能会有多个，其后「font-style:italic」这样内容时，将这个内容删除；
2、搜索内容「.mdx-vlook-load-done::before」，在其后的「display:none!important」末尾，添加「font-style:normal」
3、保存，并重新启动 Typora，选中这个修改后的主题再看看

**Comment by FrankSFLYS** [comment]
我做了这几件事：
- 升级 Typora 到正式版，没用，又降级回去了；
- 安装了你给的几个字体；
- 翻墙上了 Typora 官网（用 Typora 的时候没翻墙）。

现在字体正常了，非常感谢。
