### ISSUE TITLE
文本中标题与大纲中标题不一致

### ISSUE THREAD

**Issue by lianzhy** [MadMaxChow/VLOOK#92]
文本中标题正常。大纲中标题为  均为0.0.0.1
![image](https://user-images.githubusercontent.com/61050897/158973048-1b8a92f7-bd53-4e18-bb2c-f07b1ee8c579.png)
![image](https://user-images.githubusercontent.com/61050897/158973538-603876e9-07ef-4a55-bbfa-6fa63e0d8502.png)

**Comment by MadMaxChow** [comment]
在章节名称自动编码方面，Markdown 文档和 Word 文档的规则是一样的，按1级、2级、3级这样逐级递进。
看你上面的图是直接从第4级开始。建议按我上面的试试看看

**Comment by lianzhy** [comment]
好的，已经可以了，谢
