### ISSUE TITLE
如何停止对标题的自动编号？

### ISSUE THREAD

**Issue by jrothschild33** [MadMaxChow/VLOOK#94]
我希望自己对标题进行编号，但VLOOK自动对所有级别的标题进行了编号，如何取消自动编号？

**Comment by MadMaxChow** [comment]
下一个版本会推出自定义章节编号的功能，实现一些个性场景，如：第一章、附录A、附录B 这类的
计划在未来两周左右发布，可以关注一下

**Comment by jrothschild33** [comment]
好的，对于长篇幅并带有很多标题的文章，自动编号有点不美观，最好能使用标题的原样式，期待更新！
