### ISSUE TITLE
导出为html后本地图片不能加载，能否开发一个插件将图片路径转成base64？

### ISSUE THREAD

**Issue by ViktorHertz** [MadMaxChow/VLOOK#96]
> 先说一些题外话：不知道这个需求算不算小众，反正我在写一些课程论文、实验报告的时候，一般都是提交.docx、.pdf文件，如果能提交一个.html文件，并且这个文件还能有不错的交互，应该能让老师眼前一亮，（甚至我觉得以后应该在高校的类似作业中普及这种文件格式，因为交互很好、目录很清晰，比起.docx、.pdf强了不止一点半点）非常感谢作者开发的这款typroa增强插件~
> 只是.md文件中一有本地图片就会很棘手，总不能连图片资源文件夹一同发给老师吧，无奈:face_with_head_bandage:

我在Typroa导出设置中配置了运行自定义命令（运行了一个.jar文件），在使用其他主题导出为html后本地图片可以正常显示，使用VLOOK主题导出为html后控制台报错（浏览器为Edge）：
> Uncaught ReferenceError: devMode is not defined

并且所有内容都无法显示（包括加载动画）
个人猜测是.jar文件与VLOOK某些内容冲突了，以下是我的一些配置：
![image](https://user-images.githubusercontent.com/75928758/171154637-28a824ae-0f92-4c29-9189-bc87e4236ac2.png)
![image](https://user-images.githubusercontent.com/75928758/171154725-b1876794-7376-45a5-8f12-abab4e3ea7ad.png)

希望作者看到能优化一下🎉~

**Comment by ViktorHertz** [comment]
我尝试自己写了图片路径转base64的脚本，本地测试html文件里面的img标签的src确实变为base64码了；然而追加到typroa导出设置中的body，还是不太行，会出现
> Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D'
> Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported

之类的报错，很难受🤕

**Comment by MadMaxChow** [comment]
这个需求有现成的解决方案，浏览器可以将所有内容另存为单个网页文件的格式，具体看看浏览器中的另存为菜单的操作

**Comment by ViktorHertz** [comment]
> 这个需求有现成的解决方案，浏览器可以将所有内容另存为单个网页文件的格式，具体看看浏览器中的另存为菜单的操作

是指这三个选项吧  
![image](https://user-images.githubusercontent.com/75928758/171328101-5f42d775-12aa-46af-873b-c57347bab28c.png)
但是不管选择哪个，保存下来的网页文件里的图片资源本质上还是引用本地的，不能异地打开呢

**Comment by ViktorHertz** [comment]
嗯..但我个人还是比较看重整合为单个文件。现在的解决办法
* 一是通过一些外部工具将图片转为base64后将base64编码拷贝下来，typroa里是可以直接显示这种形式的图片的，但又发现100kb左右以上的图片的base64码typroa显示不了了。而且转base64编码的缺点是体积会比原来大10%~20%。
* 二是上传图片到图床，使用在线链接，这也是我现在使用的方法，体验还不错，缺点就是查看时要连网。
综上，还是使用图床比较合适和优雅 🎉
