### ISSUE TITLE
在typora题注是可以显示的，但导出html后无法显示

### ISSUE THREAD

**Issue by 44maker** [MadMaxChow/VLOOK#99]
![image](https://user-images.githubusercontent.com/101875427/199241808-138d9fec-a36f-46d5-807c-2d19a005172d.png)
![image](https://user-images.githubusercontent.com/101875427/199241907-46df77ba-e000-473e-a23f-99240365ae89.png)

**Comment by MadMaxChow** [comment]
方便把你这段MD文件，以及HTML发我邮箱吗？67870144@qq.com
谢谢！
